// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwSKSkdEbsO-3mB9yaYAP7qtV_ptD-WQQ',
    appId: '1:584799052658:web:94031101c88e9018f433eb',
    messagingSenderId: '584799052658',
    projectId: 'monitoring-40224',
    authDomain: 'monitoring-40224.firebaseapp.com',
    storageBucket: 'monitoring-40224.appspot.com',
    measurementId: 'G-ES8WVZHKST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCctz_ksoWUUW2T74HS8hYQmtK4gdAfeL4',
    appId: '1:584799052658:android:cd2a3525ac2236cdf433eb',
    messagingSenderId: '584799052658',
    projectId: 'monitoring-40224',
    storageBucket: 'monitoring-40224.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG9tFTLsmjm90cUwHYnQFKWcIO5Czekl0',
    appId: '1:584799052658:ios:9a8bb89c4f2810baf433eb',
    messagingSenderId: '584799052658',
    projectId: 'monitoring-40224',
    storageBucket: 'monitoring-40224.appspot.com',
    iosBundleId: 'com.proc.hma.monitoriy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG9tFTLsmjm90cUwHYnQFKWcIO5Czekl0',
    appId: '1:584799052658:ios:3b29be397e34a44df433eb',
    messagingSenderId: '584799052658',
    projectId: 'monitoring-40224',
    storageBucket: 'monitoring-40224.appspot.com',
    iosBundleId: 'com.app.monitoriy',
  );
}
